In [176]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
import warnings

# Suppress all warnings
warnings.filterwarnings("ignore")

In [177]:
matches = pd.read_csv("matches.csv", index_col = 0)
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0,0,2023,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0,0,2023,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0,1,2023,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1,1,2023,Manchester City
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,Match Report,NaN,29.0,13.0,16.4,1.0,0,0,2023,Manchester City

In [178]:
matches["team"].value_counts()

team
Manchester City             76
Crystal Palace              76
Nottingham Forest           76
Brentford                   76
Everton                     76
Wolverhampton Wanderers     76
Fulham                      76
Arsenal                     76
Brighton and Hove Albion    76
Bournemouth                 76
West Ham United             76
Manchester United           76
Newcastle United            76
Chelsea                     76
Tottenham Hotspur           76
Aston Villa                 76
Liverpool                   76
Luton Town                  38
Burnley                     38
Sheffield United            38
Leicester City              38
Leeds United                38
Southampton                 38
Name: count, dtype: int64

In [179]:
matches[matches["team"] == "Manchester City"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0,0,2023,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0,0,2023,Manchester City
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0,1,2023,Manchester City
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1,1,2023,Manchester City
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,Match Report,NaN,29.0,13.0,16.4,1.0,0,0,2023,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Leeds United,...,Match Report,NaN,17.0,6.0,18.7,2.0,0,1,2022,Manchester City
54,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3,0,Everton,...,Match Report,NaN,9.0,4.0,19.3,2.0,0,0,2022,Manchester City
56,2023-05-21,16:00,Premier League,Matchweek 37,Sun,Home,W,1,0,Chelsea,...,Match Report,NaN,15.0,2.0,18.8,0.0,0,0,2022,Manchester City
57,2023-05-24,20:00,Premier League,Matchweek 32,Wed,Away,D,1,1,Brighton,...,Match Report,NaN,13.0,4.0,13.9,0.0,0,0,2022,Manchester City
58,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,1,Brentford,...,Match Report,NaN,17.0,2.0,16.8,0.0,0,0,2022,Manchester City

In [180]:
matches["round"].value_counts()

round
Matchweek 1     40
Matchweek 30    40
Matchweek 23    40
Matchweek 24    40
Matchweek 25    40
Matchweek 18    40
Matchweek 26    40
Matchweek 27    40
Matchweek 28    40
Matchweek 31    40
Matchweek 2     40
Matchweek 32    40
Matchweek 33    40
Matchweek 29    40
Matchweek 35    40
Matchweek 36    40
Matchweek 37    40
Matchweek 34    40
Matchweek 22    40
Matchweek 21    40
Matchweek 20    40
Matchweek 19    40
Matchweek 3     40
Matchweek 4     40
Matchweek 5     40
Matchweek 6     40
Matchweek 7     40
Matchweek 8     40
Matchweek 9     40
Matchweek 10    40
Matchweek 11    40
Matchweek 12    40
Matchweek 13    40
Matchweek 14    40
Matchweek 15    40
Matchweek 16    40
Matchweek 17    40
Matchweek 38    40
Name: count, dtype: int64

In [181]:
matches.dtypes

date              object
time              object
comp              object
round             object
day               object
venue             object
result            object
gf                 int64
ga                 int64
opponent          object
xg               float64
xga              float64
poss             float64
attendance       float64
captain           object
formation         object
opp formation     object
referee           object
match report      object
notes            float64
sh               float64
sot              float64
dist             float64
fk               float64
pk                 int64
pkatt              int64
season             int64
team              object
dtype: object

In [182]:
matches["date"] = pd.to_datetime(matches["date"])
matches.dtypes

date             datetime64[ns]
time                     object
comp                     object
round                    object
day                      object
venue                    object
result                   object
gf                        int64
ga                        int64
opponent                 object
xg                      float64
xga                     float64
poss                    float64
attendance              float64
captain                  object
formation                object
opp formation            object
referee                  object
match report             object
notes                   float64
sh                      float64
sot                     float64
dist                    float64
fk                      float64
pk                        int64
pkatt                     int64
season                    int64
team                     object
dtype: object

In [183]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches["opp_code"] = matches["opponent"].astype("category").cat.codes
matches["hour"] = matches["time"].str.replace(":.+", "", regex = True).astype("int")
matches["day_code"] = matches["date"].dt.dayofweek
result_mapping = {"W": 1, "D": 2, "L": 0}
matches["target"] = matches["result"].map(result_mapping)
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0,0,2023,Manchester City,0,5,20,4,1
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0,0,2023,Manchester City,1,16,20,5,1
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,2.0,0,1,2023,Manchester City,0,18,14,6,1
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,0.0,1,1,2023,Manchester City,1,9,15,5,1
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,1.0,0,0,2023,Manchester City,0,21,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1,3,Newcastle Utd,...,0.0,0,0,2022,Southampton,0,16,14,6,0
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3,4,Nott'ham Forest,...,0.0,1,1,2022,Southampton,0,17,20,0,0
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0,2,Fulham,...,0.0,0,0,2022,Southampton,1,9,15,5,0
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1,3,Brighton,...,1.0,0,0,2022,Southampton,0,4,14,6,0
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4,4,Liverpool,...,1.0,0,0,2022,Southampton,1,12,16,6,2

In [184]:
rf = RandomForestClassifier(n_estimators = 50, min_samples_split = 10, random_state = 1)

train = matches[matches["date"] < '2024-01-01']
test = matches[matches["date"] > '2024-01-01']
predictors = ["venue_code", "opp_code", "hour", "day_code"]

rf.fit(train[predictors], train["target"])
RandomForestClassifier(min_samples_split = 10, n_estimators = 50, random_state = 1)
preds = rf.predict(test[predictors])

acc = accuracy_score(test["target"], preds)
acc

0.43989071038251365

In [185]:
combined = pd.DataFrame(dict(actual = test["target"], prediction = preds))
pd.crosstab(index = combined["actual"], columns = combined["prediction"])

prediction   0   1   2
actual
0           74  48  15
1           48  76  13
2           35  46  11

In [186]:
precision_score(test["target"], preds, average="weighted")

0.4146694677046194

In [187]:
grouped_matches = matches.groupby("team")
group = grouped_matches.get_group("Manchester City")
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0,0,2023,Manchester City,0,5,20,4,1
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0,0,2023,Manchester City,1,16,20,5,1
4,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,2.0,0,1,2023,Manchester City,0,18,14,6,1
5,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,0.0,1,1,2023,Manchester City,1,9,15,5,1
6,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,1.0,0,0,2023,Manchester City,0,21,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Leeds United,...,2.0,0,1,2022,Manchester City,1,10,15,5,1
54,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3,0,Everton,...,2.0,0,0,2022,Manchester City,0,8,14,6,1
56,2023-05-21,16:00,Premier League,Matchweek 37,Sun,Home,W,1,0,Chelsea,...,0.0,0,0,2022,Manchester City,1,6,16,6,1
57,2023-05-24,20:00,Premier League,Matchweek 32,Wed,Away,D,1,1,Brighton,...,0.0,0,0,2022,Manchester City,0,4,20,2,2
58,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,1,Brentford,...,0.0,0,0,2022,Manchester City,0,3,16,6,0

In [188]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed = 'left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset = new_cols)
    return group

cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,5,1,3.000000,1.000000,17.666667,6.000000,17.466667,0.666667,0.333333,0.333333
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,2,1,3.666667,1.666667,19.333333,7.333333,15.933333,0.333333,0.000000,0.000000
6,2022-09-03,17:30,Premier League,Matchweek 6,Sat,Away,D,1,1,Aston Villa,...,5,2,4.333333,1.666667,18.666667,8.000000,15.033333,0.333333,0.000000,0.000000
9,2022-09-17,12:30,Premier League,Matchweek 8,Sat,Away,W,3,0,Wolves,...,5,1,3.666667,1.000000,16.000000,6.000000,15.233333,0.333333,0.000000,0.000000
10,2022-10-02,14:00,Premier League,Matchweek 9,Sun,Home,W,6,3,Manchester Utd,...,6,1,3.333333,0.333333,15.333333,6.666667,17.000000,0.333333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,2024-04-28,16:30,Premier League,Matchweek 35,Sun,Away,W,2,0,Nott'ham Forest,...,6,1,4.333333,1.000000,22.666667,8.666667,16.666667,0.333333,0.333333,0.333333
52,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Home,W,5,1,Wolves,...,5,1,3.666667,0.333333,20.333333,7.666667,17.533333,0.666667,0.333333,0.333333
53,2024-05-11,12:30,Premier League,Matchweek 37,Sat,Away,W,4,0,Fulham,...,5,1,3.666667,0.333333,14.333333,7.000000,17.000000,0.666667,0.666667,0.666667
54,2024-05-14,20:00,Premier League,Matchweek 34,Tue,Away,W,2,0,Tottenham,...,1,1,3.666667,0.333333,14.666667,7.666667,17.200000,0.333333,1.000000,1.000000
55,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,West Ham,...,6,1,3.666667,0.333333,13.333333,7.333333,15.800000,0.000000,1.333333,1.333333

In [189]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling = matches_rolling.droplevel("team")

In [190]:
def add_opponent_rolling(data, cols, new_cols):
    opponent_stats = data[["team", "date"] + new_cols].rename(columns={col: f"opp_{col}" for col in new_cols})
    merged = data.merge(opponent_stats, left_on=["opponent", "date"], right_on=["team", "date"], how="left", suffixes=("", "_y"))
    return merged.drop(columns=[col for col in merged.columns if "_y" in col])

matches_rolling = add_opponent_rolling(matches_rolling, cols, new_cols)

rolling_predictors = new_cols + [f"opp_{col}" for col in new_cols]
predictors = ["venue_code", "opp_code", "hour", "day_code"] + rolling_predictors

In [191]:
matches_rolling = add_opponent_rolling(matches_rolling, cols, new_cols)

In [192]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2024-01-01']
    test = data[data["date"] > '2024-01-01']

    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual = test["target"], prediction = preds), index = test.index)

    precision = precision_score(test["target"], preds)
    return combined, precision

In [193]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,pk_rolling,pkatt_rolling,opp_gf_rolling,opp_ga_rolling,opp_sh_rolling,opp_sot_rolling,opp_dist_rolling,opp_fk_rolling,opp_pk_rolling,opp_pkatt_rolling
0,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,0.000000,0.000000,1.666667,1.333333,11.333333,4.333333,16.533333,0.333333,0.333333,0.666667
1,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,0.000000,0.000000,1.000000,1.666667,11.333333,3.666667,17.200000,0.000000,0.000000,0.000000
2,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1,3,Manchester Utd,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3,0,Brentford,...,0.000000,0.000000,2.333333,1.333333,14.000000,5.000000,14.766667,0.666667,0.333333,0.333333
4,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3,1,Tottenham,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1446,2024-04-24,19:45,Premier League,Matchweek 29,Wed,Home,L,0,1,Bournemouth,...,0.333333,0.333333,1.333333,2.333333,13.666667,3.333333,17.433333,0.666667,0.333333,0.333333
1447,2024-04-27,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Luton Town,...,0.000000,0.000000,1.333333,3.666667,9.666667,4.666667,14.833333,0.000000,0.000000,0.000000
1448,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Away,L,1,5,Manchester City,...,0.000000,0.000000,3.666667,0.333333,20.333333,7.666667,17.533333,0.666667,0.333333,0.333333
1449,2024-05-11,15:00,Premier League,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,...,0.000000,0.000000,2.333333,0.333333,17.333333,7.000000,19.233333,1.000000,0.000000,0.000000
1450,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Away,L,0,2,Liverpool,...,0.000000,0.000000,3.000000,2.333333,22.333333,9.000000,16.333333,0.333333,0.000000,0.000000

In [194]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)
combined

    actual  prediction       date     team         opponent result
29       1           0 2023-04-26  Arsenal  Manchester City      L
31       1           1 2023-05-07  Arsenal    Newcastle Utd      W
32       1           0 2023-05-14  Arsenal         Brighton      L
33       1           1 2023-05-20  Arsenal  Nott'ham Forest      L
35       2           1 2023-08-12  Arsenal  Nott'ham Forest      W
..     ...         ...        ...      ...              ...    ...
36       0           0 2023-08-21  Arsenal   Crystal Palace      W
37       0           0 2023-08-26  Arsenal           Fulham      D
38       0           1 2023-09-03  Arsenal   Manchester Utd      W
39       0           1 2023-09-17  Arsenal          Everton      W
40       0           2 2023-09-24  Arsenal        Tottenham      D

[366 rows x 6 columns]

In [195]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)
mapping["Wolverhampton Wanderers"]

'Wolves'

In [196]:
merged = combined.merge(combined, left_on = ["date", "new_team"], right_on = ["date", "opponent"])
merged

KeyError: 'new_team'

In [173]:
merged[(merged["prediction_x"] == 1) & (merged["prediction_y"] == 0)]["actual_x"].value_counts()

Series([], Name: count, dtype: int64)